CREATE TABLE IF NOT EXISTS listings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    owner_id INT UNSIGNED NOT NULL,
    title VARCHAR(200) NOT NULL,
    slug VARCHAR(220) NOT NULL DEFAULT '',
    description TEXT NOT NULL,
    address TEXT NOT NULL,
    state_id INT UNSIGNED NOT NULL,
    city_id INT UNSIGNED NOT NULL,
    postcode VARCHAR(10) DEFAULT '',
    latitude DECIMAL(10, 8) DEFAULT NULL,
    longitude DECIMAL(11, 8) DEFAULT NULL,
    price_per_night DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    min_nights TINYINT UNSIGNED NOT NULL DEFAULT 1,
    max_guests TINYINT UNSIGNED NOT NULL DEFAULT 1,
    bedrooms TINYINT UNSIGNED NOT NULL DEFAULT 1,
    bathrooms TINYINT UNSIGNED NOT NULL DEFAULT 1,
    whatsapp VARCHAR(30) DEFAULT '',
    status ENUM('draft','pending','published','rejected','suspended') NOT NULL DEFAULT 'pending',
    rejection_reason TEXT DEFAULT NULL,
    is_featured TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    featured_until TIMESTAMP NULL DEFAULT NULL,
    views INT UNSIGNED NOT NULL DEFAULT 0,
    whatsapp_clicks INT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (state_id) REFERENCES states(id),
    FOREIGN KEY (city_id) REFERENCES cities(id),
    INDEX idx_status (status),
    INDEX idx_owner (owner_id),
    INDEX idx_state_city (state_id, city_id),
    INDEX idx_featured (is_featured, featured_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
