CREATE TABLE IF NOT EXISTS featured_packages (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(100) NOT NULL,
    days INT UNSIGNED NOT NULL,
    normal_price DECIMAL(10,2) NOT NULL,
    promo_price DECIMAL(10,2) NULL DEFAULT NULL,
    is_active TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
    sort_order TINYINT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
